service: text-editor-app

provider:
 name: aws
 runtime: nodejs16.x
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1

functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY /{proxy+}
     - http: ANY /